ALTER TABLE Invoices
ALTER COLUMN IssueDate DROP NOT NULL;

ALTER TABLE Invoices
ALTER COLUMN SubTotal SET NOT NULL;

ALTER TABLE Invoices
ALTER COLUMN TaxAmount SET NOT NULL;

ALTER TABLE Invoices
ALTER COLUMN TotalAmount SET NOT NULL;



