CREATE TABLE BackgroundJobs (
    Id UUID PRIMARY KEY,
    Type TEXT NOT NULL,
    Payload TEXT NOT NULL,
    IsCompleted BOOLEAN NOT NULL DEFAULT FALSE,
    Attempts INT NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT NOW(),
    UpdatedAt TIMESTAMPTZ DEFAULT NOW()
);
