ALTER TABLE Wallets
DROP COLUMN Balance;

ALTER TABLE Wallets
ADD COLUMN AvailableBalance DECIMAL(18,4) NOT NULL DEFAULT 0;

ALTER TABLE Wallets
ADD COLUMN PendingBalance DECIMAL(18,4) NOT NULL DEFAULT 0;